import { Router } from 'express';
const router = Router();
import * as c from '../controllers/assetsController.js';
import auth from '../middleware/authenticate.js';
router.get('/', auth, c.listAssets);
router.get('/watchlist', auth, c.getWatchlist);
router.post('/watchlist/:assetId', auth, c.addToWatchlist);
router.delete('/watchlist/:assetId', auth, c.removeFromWatchlist);
router.get('/:id', auth, c.getAsset);
router.get('/:id/history', auth, c.getPriceHistory);
export default router;
